### ISSUE TITLE
Very nice extension, there is a feature request that requires two cross-directory binary comparisons

### ISSUE THREAD

**Issue by hongshui3000** [sj0000e/vscode-hexdiff#1]
Unable to compare two files across folders

**Comment by sj0000e** [comment]
I can compare /file and subdir/file2 with v1.2.231204, Can you provide more detailed information?

**Comment by hongshui3000** [comment]
Maybe I made a mistake and selected 3 files. There should be no issues with the expansion. Thanks Reply
