### ISSUE TITLE
Dialogue with right mouseclick not avaiable

### ISSUE THREAD

**Issue by CptHolzschnauz** [sj0000e/vscode-hexdiff#2]
"Compare Selected(Hexdiff)" is just not shown with right mouseclick on the file. Whatever i try, the menupoint is not visible. Intel Mac / Newest VSC / hexdiff enabled
<img width="1835" alt="hexdif" src="https://github.com/sj0000e/vscode-hexdiff/assets/68701579/0ea264fa-c337-4330-88be-79c1f9f88fe7">

**Comment by sj0000e** [comment]
you should select two files in file list, not open editors list.

**Comment by CptHolzschnauz** [comment]
Same here:
<img width="563" alt="Bildschirmfoto 2024-01-03 um 15 26 21" src="https://github.com/sj0000e/vscode-hexdiff/assets/68701579/5c41c898-e7d3-475d-be85-5cbb4f005266">
Or do I misundersand you?

**Comment by sj0000e** [comment]
Its seems that you opend the menu after selecting only one file.
To compare files, you need to select two of them.
  
1. select two files 
- click file1 and ctrl+click file2
2. right click

**Comment by CptHolzschnauz** [comment]
Now I got it! With Mac it's shift + file 1 +file 2, then right click.
May I suggest a supershort instruction in the readme?

**Comment by vanowm** [comment]
I think this issue should be re-opened.

Opened files are not always available in workspace files list.

**Comment by f-raZ0R** [comment]
please do reopen this issue, having the same problem, even in the files list
