### ISSUE TITLE
Stops after 5 lines with identical files

### ISSUE THREAD

**Issue by CptHolzschnauz** [sj0000e/vscode-hexdiff#3]
First of all (after my confusion with the GUI) i would like to thank you for your tool.
I need it to compare a HTTP downloaded .bin (Content-Type: application/octet-stream) to the original .bin.
While debug, ihad diffs and everything went as expected, hexdiff shows the files with the diffs.
After the trackdown of the bug, as the files are equal, hexdiff shows only the first 5 lines (the files are around 240 kB):
<img width="1298" alt="Bildschirmfoto 2024-01-06 um 07 43 10" src="https://github.com/sj0000e/vscode-hexdiff/assets/68701579/297b1a98-7935-4b94-aaf1-9bf4f6fd3fb2">

**Comment by sj0000e** [comment]
The default is contrast mode.
In contrast mode, only the difference + context size(64byte) is displayed.
To show the entire file, turn off contrast mode in the user settings.
To show more content before and after the differences, increase the context size in the user settings.
